((magit-diff:magit-diff-mode "--no-ext-diff" "--stat" "--show-signature")
 (magit-fetch "--prune")
 (magit-log:magit-log-mode "-n256" "--graph" "--decorate" "--show-signature")
 (magit-pull "--rebase")
 (magit-tag "--annotate")
 (rg-menu "--hidden" "--pcre2"))
