tap "derailed/k9s"
tap "github/bootstrap"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/services"
tap "jakehilborn/jakehilborn"
brew "age"
brew "gcc"
brew "open-mpi", link: false
brew "xz"
brew "openblas"
brew "adr-tools"
brew "arpack"
brew "awk"
brew "readline"
brew "awscli"
brew "azure-cli"
brew "bash"
brew "bzip2"
brew "c-ares" # async DNS library
brew "glib"
brew "hiredis"
brew "ccache" # Object-file caching compiler wrapper
brew "cheat"
brew "clang-format"
brew "coreutils"
brew "croc"
brew "curl"
brew "kubernetes-cli"
brew "devspace"
brew "docker-compose"
brew "guile"
brew "libidn2"
brew "gnutls"
brew "gobject-introspection"
brew "findutils"
brew "gh"
brew "git"
brew "git-lfs"
brew "gnu-sed"
brew "gnu-tar"
brew "libgpg-error"
brew "libgcrypt"
brew "gnupg"
brew "node"
brew "gsasl" # GNU Simple Authentication and Security Layer
brew "gzip"
brew "hadolint"
brew "hdf5"	# File format designed to store large data
brew "helm"
brew "highlight"
brew "hey"
brew "maven"
brew "ncurses"
brew "htop"
brew "ispell"
brew "jansson"
brew "jq"
brew "json5"
brew "locust"
brew "mailutils"
brew "make"
brew "markdown"
brew "moreutils"
brew "zlib"
brew "nethogs"
brew "nghttp2" # HTTP/2 C Library
brew "nmap"
brew "node-build"
brew "nodenv", args: ["HEAD"]
brew "pandoc"
brew "pidof"
brew "pigz"
brew "pre-commit"
brew "pv" # pipe viewer
brew "pyenv", args: ["HEAD"]
brew "pyenv-ccache"
brew "pyenv-virtualenv"
brew "python@3.8"
brew "ripgrep"
brew "rsync"
brew "shellcheck"
brew "shfmt"
brew "starship"
brew "step"	# Crypto and x509 Swiss-Army-Knife
brew "tcptraceroute"
brew "tmux"
brew "tree"
brew "watch"
brew "watchexec"
brew "wget"
brew "yarn"
brew "yq" # YAML query CLI
brew "zsh-syntax-highlighting"
brew "derailed/k9s/k9s"
