#!/usr/bin/env bash

# Emacs Plus must be removed before reinstalling
if [[ $OSTYPE == darwin* ]]; then
	brew uninstall emacs-plus@29
fi

# Clean up hardlinked dirs
rm -rf "$HOME/.git-templates" \
	'~' \
	"$HOME/.emacs.d/straight/versions" \
	"$HOME/Pictures/Screenshots"
