#!/usr/bin/env zsh

# Copy last commit hash to clipboard on commit
if [[ "$OSTYPE" == darwin* ]]; then
	git log -1 --format=format:%h | pbcopy
elif [[ -n "$WSL_DISTRO_NAME" ]]; then
	git log -1 --format=format:%h
fi

# Add other post-commit hooks
