name: Cached Homebrew Check

on:
  push:
    branches: [ main ]
    paths:
      - 'actions-runner-preclean.sh'
      - 'Brewfile'
      - '.github/workflows/*.yml'
  # Run every Saturday at midnight
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'macos-12'
          - 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      # Cache Homebrew directories
      - uses: actions/cache@v3
        with:
          path: |
            /opt/homebrew/bin
            /opt/homebrew/Cellar
          key: ${{ runner.os }}-${{ hashFiles('Brewfile') }}
          restore-keys: ${{ runner.os }}

      - name: Install Homebrew packages
        run: |
          # Kludge to remove pre-installed tools from GitHub Actions runner
          ./actions-runner-preclean.sh

          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/uninstall.sh)"
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          brew bundle install
          brew bundle check --verbose
