name: Setup

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
    paths:
      - 'setup.sh'
      - 'system_config.sh'
      - 'Brewfile'
      - 'Brewfile.lock.json'
      - '.github/workflows/*.yml'
  # Run every Saturday at midnight
  schedule:
    - cron: '0 0 * * 6'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'macos-10.15'
          - 'macos-11.0'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Validate syntax
        run: bash -n "*.sh"

      - name: Set XCode version
        if: contains(matrix.os, 'macos-11.0')
        run: sudo xcode-select -s "/Applications/Xcode_12.2.app"

      - name: Run setup script
        run: ./setup.sh "TEST_HOSTNAME"
