name: Setup

on:
  push:
    branches: [ main ]
    paths:
      - 'setup.sh'
      - 'system_config.sh'
      - 'Brewfile'
      - 'Brewfile.lock.json'
      - '.github/workflows/*.yml'
  # Run every Saturday at midnight
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'macos-12'
          - 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Validate syntax
        run: bash -n *.sh

      # Kludge until .NET 6 is available in macos-12 runner
      - name: Install .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.x.x'

      - name: Run setup script
        run: ./setup.sh "TEST_HOSTNAME"
