name: Setup

on:
  push:
    branches: [ main ]
    paths:
      - 'script/**'
      - '*-Brewfile'
      - '.github/workflows/*.yml'
      - '*.el'
  pull_request:
    branches: [ main ]
    paths:
      - 'script/**'
      - '*-Brewfile'
      - '.github/workflows/*.yml'
      - '*.el'
  # Run every Saturday at midnight
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  bootstrap:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'macos-26'
          - 'ubuntu-latest'
        amend-scratch:
          - 'amend'
          - 'scratch'

    steps:
      - uses: actions/checkout@v3

      - name: Validate syntax
        run: |
          FAILURE=0
          for file in script/*;
          do
            head -1 $file | grep -q bash && echo $file && bash -O extglob -n $file
            # Grep fails out with 1 if it doesn't find the pattern.
            # Bash fails out with 2 for syntax issues.
            if [[ $? -gt 1 ]]; then
              echo "$file failed test"
              FAILURE=1
            fi
          done
          exit "$FAILURE"

      - name: Remove pre-installed tools from GitHub Actions runner
        run: |
          script/actions-runner-preclean.sh

      - name: Restore applications
        id: applications-cache
        uses: actions/cache/restore@v6
        if: ${{ matrix.amend-scratch == 'amend' && runner.os == 'macOS' }}
        continue-on-error: true
        timeout-minutes: 10
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5
        with:
          path: /Applications
          key: applications-${{ runner.os }}-${{ hashFiles('macos_Brewfile') }}
          restore-keys: |
            applications-${{ runner.os }}-

      - name: Cache Homebrew downloads on macOS
        uses: actions/cache@v6
        if: ${{ matrix.amend-scratch == 'amend' && runner.os == 'macOS' }}
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5
        with:
          path: ~/Library/Caches/Homebrew
          key: homebrew-downloads-${{ runner.os }}-${{ hashFiles('Brewfile', 'codespaces_Brewfile', 'macos_Brewfile') }}
          restore-keys: |
            homebrew-downloads-${{ runner.os }}-

      - name: Cache Homebrew downloads on Linux
        uses: actions/cache@v6
        if: ${{ matrix.amend-scratch == 'amend' && runner.os == 'Linux' }}
        env:
          SEGMENT_DOWNLOAD_TIMEOUT_MINS: 5
        with:
          path: ~/.cache/Homebrew
          key: homebrew-downloads-${{ runner.os }}-${{ hashFiles('Brewfile', 'codespaces_Brewfile', 'macos_Brewfile') }}
          restore-keys: |
            homebrew-downloads-${{ runner.os }}-

      - name: Run setup script
        run: script/setup "TEST_HOSTNAME"

      - name: Save applications
        uses: actions/cache/save@v6
        if: ${{ matrix.amend-scratch == 'amend' && runner.os == 'macOS' && github.ref == 'refs/heads/main' && steps.applications-cache.outputs.cache-hit != 'true' }}
        with:
          path: /Applications
          key: applications-${{ runner.os }}-${{ hashFiles('macos_Brewfile') }}
