name: Setup

on:
  push:
    branches: [ main ]
    paths:
      - '*.sh'
      - 'Brewfile'
      - '.github/workflows/*.yml'
  # Run every Saturday at midnight
  schedule:
    - cron: '0 0 * * 6'
  workflow_dispatch:

jobs:
  bootstrap:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - 'macos-12'
          - 'ubuntu-latest'
        amend-scratch:
          - 'amend'
          - 'scratch'

    steps:
      - uses: actions/checkout@v2

      - name: Validate syntax
        run: bash -n *.sh

      # Cache Homebrew directories for amend matrix option
      - uses: actions/cache@v3
        if: ${{ matrix.amend-scratch == 'amend' }}
        with:
          path: |
            /opt/homebrew/bin
            /opt/homebrew/Cellar
            /usr/local/Cellar
            /usr/local/bin
            /usr/local/opt
          key: ${{ runner.os }}-${{ hashFiles('Brewfile') }}
          restore-keys: ${{ runner.os }}

      - name: Run setup script
        run: |
          # Kludge to remove pre-installed tools from GitHub Actions runner
          ./actions-runner-preclean.sh

          ./setup.sh "TEST_HOSTNAME"
